### ISSUE TITLE
Appears hostapd crashing on kernels < 4.4

### ISSUE THREAD

**Issue by JasonT223** [martinsauter/WLAN-VPN-Pi#7]
Hi,

Thank you for such a great project. I used this successfully about 1 year ago. 
I recently tried to reinstall when past SD card was corrupted. I'm using a Raspberry Pi 2 with Raspbian Jessie. I am using two Edimax EW-7811Un USB wireless sticks.

I saw the instructions to downgrade kernel to something less than or equal to 4.1. Followed with a reboot and running command "uname -a" to confirm lower kernel version.

Next, I ran the install script followed by reboot. Running "uname -a" again I see the kernel is back to 4.4+. I downgraded kernel again and followed with reboot.  Running "uname -a" again I see kernel 4.1 in place. (I have also tried kernel 3.1.18). 

However, upon reboot the access point "Pi_AP" only shows up for a few seconds. I have tried to connect immediately and will not connect. 

I saw the other issue posted earlier about discovering the kernel issue and the reference to process "hostapd". So looking in syslog I see several references to hostapd where it appears it has issues. 

Aug 22 13:48:11 raspberrypi hostapd[574]: Starting advanced IEEE 802.11 management: hostapd
Aug 22 13:48:11 raspberrypi systemd[1]: hostapd.service: control process exited, code=killed status=9
Aug 22 13:48:11 raspberrypi systemd[1]: Failed to start LSB: Advanced IEEE 802.11 management daemon.
Aug 22 13:48:11 raspberrypi systemd[1]: Unit hostapd.service entered failed state.

Any thoughts or suggestions for me to investigate? I can also post full contents of syslog if that helps.

**Comment by martinsauter** [comment]
That doesn't sound good. I'll give it a try myself and get back to you. Could take a couple of days though.

**Comment by JasonT223** [comment]
Great, thank you!

Here is what I have tried since I posted the issue.
- Clean install of Raspian Jessie
- Downgraded kernel to 3.18.16-v7
- Expanded file system
- Commited these to lines in the install script to see if that prevented upgrading the kernel after reboot to the 4.4 version and it seemed to work. After reboot, kernel still at 3.18.
#apt-get -y install htop tcpdump
#apt-get -y upgrade

However, the access point only seems to run for a few seconds as I can see "Pi_AP" on my laptop and phone but does not let me connect. 

Next, I started from a clean install repeating all steps above except I committed out the lines in the install script that install hostapd. I found a different source and compiled. 
This allowed hostapd to keep running but when I try to connect I get a message "Obtaining IP address" that does not go away so I am unable to connect. 

I apologize I am not a programmer and hope this information is helpful. Thank you again for this project.

**Comment by martinsauter** [comment]
O.k. here's how you can fix it: Download the Raspian Jessie Lite image from March 2016. It comes with Kernel 4.1 and still works. 

  http://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2016-03-18/

hostapd is broken by newer images... No idea why. 

Note: I'm still getting this error message:

   raspberrypi systemd[1]: hostapd.service: control process exited, code=killed status=9_

but hostapd still works so it doesn't seem to be related.

Don't use rpi-update, it will break hostapd functionality.

Obviously it would be really good to figure out why newer images brake things as this can just be a temporary fix. But better than nothing for the moment...

**Comment by JasonT223** [comment]
Great, thank you for looking into this. I will try this.

**Comment by JasonT223** [comment]
Your recommendations worked. Excellent! Thank you again!
